#!/bin/sh -e

PREFIX=""
if [ -d "venv" ] ; then
    PREFIX="venv/bin/"
fi
SOURCE_FILES="scraper.py"

GREEN="\033[32m"
NC="\033[0m" # No Color

if [[ "$1" = "yes" ]]
then
    echo "${GREEN}Formating ${NC}code..."
    ${PREFIX}black -t py37 $SOURCE_FILES
    echo "${GREEN}Sorting ${NC}imports..."
    ${PREFIX}isort -rc -y $SOURCE_FILES
else
    echo "${GREEN}Checking ${NC}code format..."
    ${PREFIX}black -t py37 --check --diff $SOURCE_FILES
    echo "${GREEN}Checking ${NC}imports order..."
    ${PREFIX}isort -c -df -rc $SOURCE_FILES
    echo "${GREEN}Checking ${NC}static type..."
    ${PREFIX}mypy scraper.py
fi
